apiVersion: v1
kind: Service
metadata:
  name: service-production
  namespace: laa-criminal-applications-datastore-production
  labels:
    app: laa-criminal-applications-datastore-web-production
spec:
  ports:
  - port: 80
    name: http
    targetPort: 3000
  selector:
    app: laa-criminal-applications-datastore-web-production
