require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'
    - 'vendor/**/*'

####################################
## Customization for this project ##
####################################

# Disabled cops
###############

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

# Enabled but tweaked cops
##########################

# To be tweaked until we find the right balance
Metrics/MethodLength:
  Max: 12

Metrics/ParameterLists:
  Max: 6

Metrics/BlockLength:
  AllowedMethods: resource
# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/HashSyntax
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: consistent

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Naming/BlockForwarding
Naming/BlockForwarding:
  EnforcedStyle: explicit

Rails/DynamicFindBy:
  AllowedMethods:
    - find_by_pages

Rails/ActiveRecordAliases:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/MultipleExpectations:
  Max: 7

RSpec/NestedGroups:
  Max: 6

RSpec/ExampleLength:
  Max: 16

RSpec/DescribeClass:
  Exclude:
    - '**/spec/api/**/*'

Rails/SkipsModelValidations:
  Exclude:
    - '**/spec/api/datastore/v2/list_applications_spec.rb'
    - '**/spec/api/datastore/v2/searches/*'
