pidfile: tmp/pids/shoryuken.pid

# Number of threads available for processing messages at a time
concurrency: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>

# Seconds to pause fetching from, when a queue is empty
delay: 5

# Only queues that are used for jobs
queues:
  - datastore_submissions
