apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb
  namespace: laa-criminal-applications-metabase
spec:
  maxUnavailable: 50%
  selector:
    matchLabels:
      app: laa-criminal-applications-metabase-web
