apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-staging
  namespace: laa-criminal-applications-datastore-staging
data:
  ENV_NAME: staging
  RACK_ENV: production
  RAILS_ENV: production
  RAILS_SERVE_STATIC_FILES: enabled
  ENABLE_PROMETHEUS_EXPORTER: "true"
  # Datastore is accessed via local cluster networking (no SSL)
  DISABLE_HTTPS: enabled
  MAAT_API_API_URL: https://laa-crime-applications-adaptor-uat.apps.live.cloud-platform.service.justice.gov.uk
  MAAT_API_OAUTH_URL: https://caa-api-uat.auth.eu-west-2.amazoncognito.com
