apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-staging
  namespace: laa-criminal-applications-datastore-staging
data:
  ENV_NAME: staging
  RACK_ENV: production
  RAILS_ENV: production
  RAILS_SERVE_STATIC_FILES: enabled
  ENABLE_PROMETHEUS_EXPORTER: "true"
  # Datastore is accessed via local cluster networking (no SSL)
  DISABLE_HTTPS: enabled
