apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-staging
  namespace: laa-criminal-applications-datastore-staging
spec:
  maxUnavailable: 50%
  selector:
    matchLabels:
      app: laa-criminal-applications-datastore-web-staging
