# Prometheus Alerts
#
# https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html
#
# Note: we are using a regex in the namespace to filter and trigger alerts
# in both, staging and production environments.
#
# To see the current alerts in this namespace:
#   kubectl describe prometheusrule -n laa-criminal-applications-datastore-staging
#
# Alerts will be sent to the slack channel: #laa-crime-apply-alerts
#
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-rules
  namespace: laa-criminal-applications-datastore-staging
  labels:
    role: alert-rules
    prometheus: cloud-platform
spec:
  groups:
  - name: application-rules
    rules:
    - alert: CrimeApplyDatastore-DeploymentReplicasMismatch
      expr: >-
        kube_deployment_spec_replicas{job="kube-state-metrics", namespace=~"^laa-criminal-applications-datastore.*"}
        != kube_deployment_status_replicas_available{job="kube-state-metrics"}
      for: 30m
      labels:
        severity: laa-crime-apply-alerts
      annotations:
        message: Deployment `{{ $labels.deployment }}` has not matched the expected number of replicas for more than 30m.

    - alert: CrimeApplyDatastore-KubePodCrashLooping
      expr: >-
        rate(kube_pod_container_status_restarts_total{job="kube-state-metrics", namespace=~"^laa-criminal-applications-datastore.*"}[5m]) > 0
      for: 5m
      labels:
        severity: laa-crime-apply-alerts
      annotations:
        message: Pod `{{ $labels.pod }}` has been restarting in `{{ $labels.namespace }}` for the last 5m.

    - alert: CrimeApplyDatastore-KubeQuotaExceeded
      expr: >-
        100 * kube_resourcequota{job="kube-state-metrics", type="used", namespace=~"^laa-criminal-applications-datastore.*"} 
        / ignoring(instance, job, type) (kube_resourcequota{job="kube-state-metrics", type="hard"} > 0) > 90
      for: 5m
      labels:
        severity: laa-crime-apply-alerts
      annotations:
        message: Namespace `{{ $labels.namespace }}` is using {{ printf "%0.0f" $value}}% of its {{ $labels.resource }} quota.

    - alert: CrimeApplyDatastore-KubePodNotReady
      expr: >-
        sum by (namespace, pod) (kube_pod_status_phase{namespace=~"^laa-criminal-applications-datastore.*", job="kube-state-metrics", phase=~"Pending|Unknown"}) > 0
      for: 1h
      labels:
        severity: laa-crime-apply-alerts
      annotations:
        message: Pod `{{ $labels.pod }}` in `{{ $labels.namespace }}` has been in a non-ready state for longer than 1h.

    - alert: CrimeApplyDatastore-TrivyVulns
      expr: >-
        sum by (namespace, image_tag, trivy_severity) (
          label_replace(
            trivy_image_vulnerabilities{namespace=~"^laa-criminal-applications-datastore.*",severity=~"Critical|High"}
          >
            0,
          "trivy_severity",
          "$1",
          "severity",
          "(.*)"
          )
        )
      for: 1h
      labels:
        severity: laa-crime-apply-alerts
      annotations:
        message: Image `{{ $labels.image_tag }}` in namespace `{{ $labels.namespace }}` has {{ $value }} {{ $labels.trivy_severity }} vulnerabilities.
        dashboard_url: https://grafana.live.cloud-platform.service.justice.gov.uk/d/trivy_starboard_operator123/trivy-operator-image-vulnerability?orgId=1&from=now-24h&to=now&var-namespace={{ $labels.namespace }}

    - alert: CrimeApplyDatastore-DLQNotEmpty
      expr: >-
        sum(aws_sqs_approximate_number_of_messages_visible_maximum{queue_name=~"^laa-crime-apply-(staging|production)-application-events-dlq"} offset 5m) 
        by (queue_name) > 0
      for: 10m
      labels:
        severity: laa-crime-apply-alerts
      annotations:
        message: Dead letter queue `{{ $labels.queue_name }}` has {{ $value }} message(s).
        dashboard_url: https://grafana.live.cloud-platform.service.justice.gov.uk/d/AWSSQS000/aws-sqs?orgId=1&from=now-24h&to=now&var-datasource=Cloudwatch&var-region=default&var-queue={{ $labels.queue_name }}

    - alert: CrimeApplyDatastore-PrometheusExporterFailure
      expr: >-
        ruby_collector_working{namespace=~"^laa-criminal-applications-datastore.*"} != 1
      for: 30m
      labels:
        severity: laa-crime-apply-alerts
      annotations:
        message: Prometheus exporter not working in pod `{{ $labels.pod }}` for more than 30m.
